#%RAML 1.0
title: ImageStoreRepo
version: 0.1
baseUri: http://info3103.cs.unb.ca/
types:
  userPicture:
    type: file
    fileTypes: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
  user: 
    type : object
    properties: 
      name: 
        type: string
        required: true
      username:
        type: string
        required: true
      password:
        type: string
        required: true



/ :  
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message" : "Welcome to the Image Store Repo. Go to /signin POST
  to sign in"
              }


/signin:
  post:
    description: Login to create new user session
    body: 
      application/json:
        example: |
     
          "username" : "jsmith32",
          "password" : "password1234"
        }
    responses: 
      201:
        body: 
          application/json:
            example: |
            {
              "status" : "success"
            }
      400:
        body: 
          application/json:
            example: |
            {
              "message" : "Bad Request"
            }
      500:
        body: 
          application/json:
            example: |
            {
              "message" : "Internal Server Error"
            }

  get:
    description: Check if logged in
    queryParameters:
      session_token:
              description: Session token provided by the authenticated session
              type: string
              required: true
    responses:
      200:
        body:
          application/json:
            example: |
            {
              "status" : "success"
            }
      403:
        body: 
          application/json:
            example: |
            {
              "status" : "fail"
            }
  delete:
    description: Delete a valid session (Logout)
    queryParameters:  
      session_token:
              description: Session token provided by the authenticated session
              type: string
              required: true
    responses:
      204:
      403:
        body: 
          application/json:
            example: |
            {
              "status" : "fail", "message" : "Must sign in"
            }

  /{userId}:
    delete:
      description: Delete a User
      queryParameters: 
        session_token:
              description: Session token provided by the authenticated session
              type: string
      responses: 
        204:
        403:
          body: 
            application/json:
              example: |
              {
                "status" : "fail", "message": "Not authorized to view this resource"
              }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Resource not found"
                }
        500:
          body: 
            application/json:
              example: |
              {
                "message" : "Internal Server Error"
              }


    /images:
      get:
        description: Retrieve list of images, or a specific image with provided id
        queryParameters:
          session_token:
            description: Session token provided by the authenticated session
            type: string
            required: true 
          imageId: 
            type: number
            required: false
          responses:
            200:
              body:
                application/json:
                  example: |
                  {
                    "images" : [
                      { "path" : "/users/1/images/123",
                        "description" : "Day at the beach",
                        "filetype": "jpg"

                      },
                      { "path" : "/users/1/images/23",
                        "description" : "My favourite Motorcycle",
                        "filetype": "png"
                      }
                    ]
                  }
            404:
              body:
                application/json:
                  example: |
                  {
                    "message" : "Resource not found"
                  }
      post:
        description: Create a new image
        queryParameters: 
          session_token:
            description: Session token provided by the authenticated session
            type: string
            required: true
        body: 
          multipart/form-data:
            properties: 
              file:
                description: The image to be uploaded
                required: true
                type: file
                example: !include beach.jpg
              description:
                description: An optional description for the image
                required: false
                type: string
                example: Fun day at the beach
        
        responses: 
          201:
            body: 
              application/json:
                example: |
                {
                  "path" : "/users/1/images/456"
                }
          400:
            body: 
              application/json:
                example: |
                {
                  "message" : "Bad Request: Check Post Structure"
                }
          500:
            body: 
              application/json:
                example: |
                {
                  "message" : "Internal Server Error: Image Creation Unsuccessful"
                }

          
          

      /{imageId}:
        get:
          description: Return an image file
          queryParameters: 
            session_token:
              description: Session token provided by the authenticated session
              type: string
              required: true
          body:
            200:
              body:
                image/jpeg:
                  type: userPicture
            404:
              body:
                application/json:
                  example: |
                  {
                    "message" : "Resource Not Found"
                  }
            

        delete:
          description: Delete an image
          queryParameters: 
            session_token:
              description: Session token provided by the authenticated session
              type: string
              required: true
          responses:
            204:
              
            404:
              body: 
                  application/json:
                    example: |
                    {
                      "message": "Resource not found"
                    }
            500:
              body: 
                application/json:
                  example: |
                  {
                    "message" : "Internal Server Error"
                  }
            
                    

